# Generated by Django 4.1.3 on 2023-01-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApkFinal1', '0005_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('subtitulo', models.CharField(max_length=250)),
                ('texto', models.TextField()),
                ('imagen', models.ImageField(upload_to='media')),
                ('autor', models.CharField(max_length=250)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
