# Generated by Django 4.1.3 on 2023-01-18 21:11

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApkFinal1', '0006_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='texto',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
