# Generated by Django 4.1.3 on 2023-01-18 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApkFinal1', '0007_alter_blog_texto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
