# Generated by Django 4.1.3 on 2023-01-19 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApkFinal1', '0008_delete_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('subtitulo', models.CharField(max_length=250)),
                ('texto', models.CharField(max_length=255)),
                ('imagen', models.ImageField(upload_to='')),
                ('autor', models.CharField(max_length=250)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
